#ifndef AUTOGENERATED_H
#define AUTOGENERATED_H

#include <string>

// Item 5: Know what functions C++ silently writes and calls
// This class doesn't define any special functions
// Compiler will generate: default constructor, copy constructor, 
// copy assignment operator, and destructor
class AutoGenerated {
private:
    int value;
    std::string text;

public:
    AutoGenerated(int v, const std::string& t) : value(v), text(t) {}
    
    // Compiler generates:
    // - Default constructor (if no constructors defined)
    // - Copy constructor
    // - Copy assignment operator
    // - Destructor
    
    void display() const;
};

// Item 5: Explicitly defined functions
class ExplicitFunctions {
private:
    int value;
    std::string text;

public:
    // Explicitly define all special functions
    ExplicitFunctions(int v = 0, const std::string& t = "");
    ExplicitFunctions(const ExplicitFunctions& other);
    ExplicitFunctions& operator=(const ExplicitFunctions& other);
    ~ExplicitFunctions();
    
    void display() const;
};

#endif // AUTOGENERATED_H
