#include "../include/AutoGenerated.h"
#include <iostream>

void AutoGenerated::display() const {
    std::cout << "AutoGenerated: value=" << value 
              << ", text=" << text << "\n";
}

// Explicit implementation of special functions
ExplicitFunctions::ExplicitFunctions(int v, const std::string& t) 
    : value(v), text(t) {
    std::cout << "ExplicitFunctions: Constructor called\n";
}

ExplicitFunctions::ExplicitFunctions(const ExplicitFunctions& other) 
    : value(other.value), text(other.text) {
    std::cout << "ExplicitFunctions: Copy constructor called\n";
}

ExplicitFunctions& ExplicitFunctions::operator=(const ExplicitFunctions& other) {
    std::cout << "ExplicitFunctions: Copy assignment operator called\n";
    if (this != &other) {
        value = other.value;
        text = other.text;
    }
    return *this;
}

ExplicitFunctions::~ExplicitFunctions() {
    std::cout << "ExplicitFunctions: Destructor called\n";
}

void ExplicitFunctions::display() const {
    std::cout << "ExplicitFunctions: value=" << value 
              << ", text=" << text << "\n";
}
