#include <iostream>
#include "../include/Person.h"
#include "../include/AutoGenerated.h"
#include "../include/NoCopy.h"

int main() {
    std::cout << "=== Item 4: Object Initialization ===\n";
    Person p1("John Doe", 30, 1.75);
    p1.display();
    std::cout << "\n";

    std::cout << "=== Item 5: Compiler-Generated Functions ===\n";
    AutoGenerated ag1(42, "Hello");
    ag1.display();
    
    // Copy constructor (compiler-generated)
    AutoGenerated ag2 = ag1;
    ag2.display();
    
    // Copy assignment (compiler-generated)
    AutoGenerated ag3(0, "");
    ag3 = ag1;
    ag3.display();
    std::cout << "\n";

    std::cout << "=== Item 5: Explicit Functions ===\n";
    ExplicitFunctions ef1(100, "Test");
    ExplicitFunctions ef2 = ef1;  // Copy constructor
    ExplicitFunctions ef3;
    ef3 = ef1;  // Copy assignment
    std::cout << "\n";

    std::cout << "=== Item 6: Disallow Copying ===\n";
    NoCopy nc1(1, "Resource1");
    nc1.display();
    
    // The following lines would cause compilation errors:
    // NoCopy nc2 = nc1;  // Error: copy constructor is deleted
    // NoCopy nc3(2, "Resource2");
    // nc3 = nc1;  // Error: copy assignment is deleted
    
    std::cout << "NoCopy instances cannot be copied (would cause compile error)\n";
    std::cout << "\n";

    return 0;
}
